// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYofaHhKnt-ttHmXnk3vI82HPl3ezl3QA',
    appId: '1:285994038266:android:dc3570e9aa2bf659dc6a43',
    messagingSenderId: '285994038266',
    projectId: 'librarybook-e46e0',
    databaseURL: 'https://librarybook-e46e0.firebaseio.com',
    storageBucket: 'librarybook-e46e0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZmfkrgXQ7PActSV5mR0P3ob8AzW-Vs0o',
    appId: '1:285994038266:ios:8c034609de1968ccdc6a43',
    messagingSenderId: '285994038266',
    projectId: 'librarybook-e46e0',
    databaseURL: 'https://librarybook-e46e0.firebaseio.com',
    storageBucket: 'librarybook-e46e0.appspot.com',
    iosClientId: '285994038266-90pemi9jukspdupuk1ro16ar8tibgms2.apps.googleusercontent.com',
    iosBundleId: 'com.khairudin.libraryBook',
  );
}
